version: 2.1

orbs:
  snyk: snyk/snyk@1.5.0
  slack: circleci/slack@4.12.5
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: pytest test_app.py

  snyk-scan:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install -r requirements.txt
      - snyk/scan:
          command: "--file=requirements.txt --package-manager=pip"

  sonar-scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
            unzip sonar-scanner.zip -d $HOME
            echo 'export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"' >> $BASH_ENV
      # - run:
      #     name: Run SonarQube Scan
      #     command: |
      #       source $BASH_ENV
      #       sonar-scanner \
      #         -Dsonar.projectKey=idt-demo \
      #         -Dsonar.sources=. \
      #         -Dsonar.host.url=$SONAR_HOST_URL \
      #         -Dsonar.login=$SONAR_TOKEN

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Upload to S3
          command: |
            zip -r app.zip app.py
            aws s3 cp app.zip s3://$S3_BUCKET_NAME/app.zip

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: always
          template: basic_success_1

workflows:
  build-deploy:
    jobs:
      - build-and-test
      - snyk-scan:
          requires:
            - build-and-test
      - sonar-scan:
          requires:
            - snyk-scan
      - deploy:
          requires:
            - sonar-scan
      - notify:
          requires:
            - deploy
